package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the type/category of attribute a product variant can have.
 *
 * <p>Examples include Color, Size, Flavor, Gender, or Style.</p>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(name = "attribute_types")
public class AttributeType {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // attribute type name shown to users
    @Column(nullable = false, unique = true)
    private String name;

    // optional explanation of what this attribute type represents
    @Column
    private String description;

    // tracks whether this attribute type is currently active
    @Column(nullable = false)
    private boolean active = true;
}