package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an allowed value for an attribute type.
 *
 * <p>Examples include Black for Color, Medium for Size, or Vanilla for Flavor.</p>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(
    name = "attribute_values", 
    uniqueConstraints = {
        @UniqueConstraint(columnNames = {"attribute_type_id", "value"})
    }
)
public class AttributeValue {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // actual attribute value shown to users
    @Column(nullable = false)
    private String value;

    // many values can belong to one attribute type
    @ManyToOne
    @JoinColumn(name = "attribute_type_id", nullable = false)
    private AttributeType attributeType;

    // display order for dropdowns or lists
    @Column(nullable = false)
    private int displayOrder;

    // tracks whether this attribute value is currently active
    @Column(nullable = false)
    private boolean active = true;
}