package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a top-level product grouping.
 * 
 * <p>Broad groups like Merchandise, Beverages, or Supplements. More specific organization is
 * handled by Subcategory.</p>
 */
@Data // Lombok: auto gen getter & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor  
@Entity // JPA: maps class to database table
@Table(name = "categories")
public class Category {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // category name shown to users; must be unique
    @Column(nullable = false, unique = true)
    private String name; 

    // optional description
    @Column
    private String description;
}
