package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a general product being sold.
 *
 * <p>Examples include Hoodies, Energy Drinks, or Protein Powder.</p>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(name = "products")
public class Product {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // subcategory name shown to users
    @Column(nullable = false, unique = true)
    private String name;

    // optional description
    @Column
    private String description;

    // active status
    @Column(nullable = false)
    private boolean active = true;

    // many products can belong to one subcategory
    @ManyToOne
    @JoinColumn(name = "subcategory_id", nullable = false)
    private Subcategory subcategory;
}
