package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents the exact sellable inventory item.
 *
 * <p>Examples include a black medium hoodie, lemon bucked up energy, vanilla protein powder.
 * Inventory quantity, price, SKU, and reorder information belong here instead of Product.</p>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(name = "product_variants")
public class ProductVariant {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // many variants can belong to one product
    @ManyToOne
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    // optional unique identifier for tracking specific inventory items
    @Column(unique = true)
    private String sku;

    // readable variant name shown to users, like "Black / Medium"
    @Column(name = "display_name", nullable = false)
    private String displayName;

    // current inventory count for this exact variant
    @Column(name = "quantity_on_hand", nullable = false)
    private int quantityOnHand;

    // low stock warning level for this exact variant
    @Column(name = "low_stock_threshold", nullable = false)
    private int lowStockThreshold;

    // tracks whether this variant is currently active
    @Column(nullable = false)
    private boolean active = true;
}