package com.hwinterton.inventory_api.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents one level more specific grouping than category, under category type. 
 * 
 * <p>Represents more specific groups like Hoodie, Energy Drinks, Protein Powder</p>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(name = "subcategories")
public class Subcategory {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // subcategory name shown to users
    @Column(nullable = false, unique = true)
    private String name;

    // optional description
    @Column
    private String description;

    // many subcategories can belong to one category
    @ManyToOne // this is how we say "subcategory HAS-A category object"
    @JoinColumn(name = "category_id", nullable = false)
    private Category category; 
}
