package com.hwinterton.inventory_api.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Connects a specific AttributeValue (and thus AttributeType) to a ProductVariant.
 *
 * <p>Allows variants to flexibly store attributes like Color, Size, or Flavor
 * without hardcoding those fields directly into ProductVariant.</p>
 *
 * <pre>
 * ProductVariant -> AttributeType + AttributeValue
 *
 * Black Hoodie -> Color + Black
 * Black Hoodie -> Size + Medium
 * Vanilla Protein Powder -> Flavor + Vanilla
 * </pre>
 */
@Data // Lombok: auto gen getters & setters
@NoArgsConstructor // Lombok: auto gen no-args constructor
@Entity // JPA: maps class to database table
@Table(
    name = "variant_attributes",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = {"product_variant_id", "attribute_value_id"})
    }
)
public class VariantAttribute {

    // primary key generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // many variant attributes can belong to one product variant
    @ManyToOne
    @JoinColumn(name = "product_variant_id", nullable = false)
    private ProductVariant productVariant;

    // many variant attributes can reference one attribute value
    @ManyToOne
    @JoinColumn(name = "attribute_value_id", nullable = false)
    private AttributeValue attributeValue;
}