spring.application.name=inventory-api

# profiles help create different configurations based on desired outcomes / activities being done
# ie: testing, development, and so on.
spring.profiles.active=local


# This is my database configuration profile
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false